alter table ANNOTATIONS drop foreign key FK47010F047A0F4E9E;
alter table ANNOTATIONS drop foreign key FK47010F04491771CA;
alter table ANSWERS drop foreign key FKF8494455EBCBF05;
alter table ANSWERS drop foreign key FKF8494455C3F6856A;
alter table ASSIGNMENTS drop foreign key FKE898E726B78970AA;
alter table ASSIGNMENT_MATERIAL_ASSOCS drop foreign key FK23C7F7A4645FAC0A;
alter table ASSIGNMENT_MATERIAL_ASSOCS drop foreign key FK23C7F7A4491771CA;
alter table ASSIGNMENT_RESPONSES drop foreign key FK6F169540645FAC0A;
alter table ASSIGNMENT_RESPONSES drop foreign key FK6F1695407A0F4E9E;
alter table COMMENTS drop foreign key FKABDCDF4EBCBF05;
alter table COMMENTS drop foreign key FKABDCDF459F0726A;
alter table COMMENTS drop foreign key FKABDCDF47A0F4E9E;
alter table CUSTOM_FIELDS drop foreign key FK8566DF47F856EB76;
alter table CUSTOM_FIELD_VALUES drop foreign key FKABA1663534907427;
alter table CUSTOM_FIELD_VALUES drop foreign key FKABA16635491771CA;
alter table MATERIALS drop foreign key FKCEB1500CF856EB76;
alter table QUESTIONS drop foreign key FK3BDD512D645FAC0A;
alter table QUESTION_MATERIAL_ASSOCS drop foreign key FKF0DF5EBD491771CA;
alter table QUESTION_MATERIAL_ASSOCS drop foreign key FKF0DF5EBDC3F6856A;
alter table TASTY_ITEMS drop foreign key FK141602EC8DF4AFE6;
alter table TASTY_ITEMS drop foreign key FK141602ECA9042904;
alter table TASTY_ITEM_TAGS drop foreign key FK4312F31173F1FE90;
alter table TASTY_ITEM_TAGS drop foreign key FK4312F311A24B5E75;
alter table TASTY_ITEM_TAGS drop foreign key FK4312F31136904DB0;
alter table TASTY_ITEM_TAGS drop foreign key FK4312F311558D87E4;
alter table TASTY_TAGS drop foreign key FK74477F4DDB4B49FF;
alter table TASTY_TAGS drop foreign key FK74477F4DA9042904;
alter table TASTY_USERS drop foreign key FK14BEA93470CE42E;
alter table TASTY_USERS drop foreign key FK14BEA934A9042904;
alter table TASTY_USER_ITEMS drop foreign key FK6650E60AFADF2B0;
alter table TASTY_USER_ITEMS drop foreign key FK6650E6036904DB0;
alter table TASTY_USER_ITEMS drop foreign key FK6650E60918555F4;
alter table TASTY_USER_ITEMS drop foreign key FK6650E60917FE53C;
alter table TASTY_USER_ITEM_TAGS drop foreign key FK17472485AFADF2B0;
alter table TASTY_USER_ITEM_TAGS drop foreign key FK1747248536904DB0;
alter table TASTY_USER_ITEM_TAGS drop foreign key FK17472485558D87E4;
alter table TASTY_USER_TAGS drop foreign key FKD6EF3559AFADF2B0;
alter table TASTY_USER_TAGS drop foreign key FKD6EF355981C6CED8;
alter table TASTY_USER_TAGS drop foreign key FKD6EF3559B0259F75;
alter table TASTY_USER_TAGS drop foreign key FKD6EF3559558D87E4;
alter table UCM_COURSE_WORKSITE_AFFILS drop foreign key FK27FF1C12F6DA3530;
alter table UCM_COURSE_WORKSITE_AFFILS drop foreign key FK27FF1C12C0468FD0;
alter table UCM_PARTICIPANTS drop foreign key FKF04F6860F6DA3530;
alter table UCM_PARTICIPANTS drop foreign key FKF04F68609383750;
alter table UCM_WORKSITES drop foreign key FK8D3744BBBD2267B0;
alter table UNITS drop foreign key FK4D25F4FF856EB76;
alter table UNIT_MATERIAL_ASSOCS drop foreign key FK6ECC085BB78970AA;
alter table UNIT_MATERIAL_ASSOCS drop foreign key FK6ECC085B491771CA;
drop table if exists ANNOTATIONS;
drop table if exists ANSWERS;
drop table if exists ASSIGNMENTS;
drop table if exists ASSIGNMENT_MATERIAL_ASSOCS;
drop table if exists ASSIGNMENT_RESPONSES;
drop table if exists COMMENTS;
drop table if exists CUSTOM_FIELDS;
drop table if exists CUSTOM_FIELD_VALUES;
drop table if exists MATERIALS;
drop table if exists PARTICIPANTS;
drop table if exists QUESTIONS;
drop table if exists QUESTION_MATERIAL_ASSOCS;
drop table if exists TASTY_ITEMS;
drop table if exists TASTY_ITEM_TAGS;
drop table if exists TASTY_SERVICES;
drop table if exists TASTY_TAGS;
drop table if exists TASTY_USERS;
drop table if exists TASTY_USER_ITEMS;
drop table if exists TASTY_USER_ITEM_TAGS;
drop table if exists TASTY_USER_TAGS;
drop table if exists UCM_COURSES;
drop table if exists UCM_COURSE_WORKSITE_AFFILS;
drop table if exists UCM_PARTICIPANTS;
drop table if exists UCM_TERMS;
drop table if exists UCM_USERS;
drop table if exists UCM_WORKSITES;
drop table if exists UNITS;
drop table if exists UNIT_MATERIAL_ASSOCS;
drop table if exists USERS;
drop table if exists WORKSITES;
create table ANNOTATIONS (ANNOTATION_ID bigint not null auto_increment, MATERIAL_ID bigint, PARTICIPANT_ID bigint, CLIP_BEGIN varchar(255), CLIP_END varchar(255), DATE_MODIFIED datetime, text text, title varchar(255), type varchar(255), primary key (ANNOTATION_ID)) type=InnoDB;
create table ANSWERS (ANSWER_ID bigint not null auto_increment, ASSIGNMENT_RESPONSE_ID bigint, QUESTION_ID bigint, STATUS integer, text0 text, text1 text, text2 text, text3 text, text4 text, text5 text, text6 text, text7 text, text8 text, text9 text, text10 text, text11 text, text12 text, text13 text, text14 text, text15 text, primary key (ANSWER_ID), unique (ASSIGNMENT_RESPONSE_ID, QUESTION_ID)) type=InnoDB;
create table ASSIGNMENTS (ASSIGNMENT_ID bigint not null auto_increment, UNIT_ID bigint, CUSTOM_TYPE varchar(255), DATE_DUE datetime, instructions text, ORDINAL_VALUE integer, title varchar(255), type varchar(255), primary key (ASSIGNMENT_ID)) type=InnoDB;
create table ASSIGNMENT_MATERIAL_ASSOCS (ASSIGNMENT_MATERIAL_ASSOC_ID bigint not null auto_increment, MATERIAL_ID bigint, ASSIGNMENT_ID bigint, primary key (ASSIGNMENT_MATERIAL_ASSOC_ID)) type=InnoDB;
create table ASSIGNMENT_RESPONSES (ASSIGNMENT_RESPONSE_ID bigint not null auto_increment, ASSIGNMENT_ID bigint, PARTICIPANT_ID bigint, DATE_SUBMITTED datetime, STATUS integer, text0 text, text1 text, text2 text, text3 text, text4 text, text5 text, text6 text, text7 text, text8 text, text9 text, text10 text, text11 text, text12 text, text13 text, text14 text, text15 text, primary key (ASSIGNMENT_RESPONSE_ID), unique (ASSIGNMENT_ID, PARTICIPANT_ID)) type=InnoDB;
create table COMMENTS (COMMENT_ID bigint not null auto_increment, ANSWER_ID bigint, ASSIGNMENT_RESPONSE_ID bigint, PARTICIPANT_ID bigint, DATE_MODIFIED datetime, STATUS integer, text text, type varchar(255), primary key (COMMENT_ID)) type=InnoDB;
create table CUSTOM_FIELDS (CUSTOM_FIELD_ID bigint not null auto_increment, WORKSITE_ID bigint, name varchar(255), ORDINAL_VALUE integer, visibility integer, primary key (CUSTOM_FIELD_ID)) type=InnoDB;
create table CUSTOM_FIELD_VALUES (CUSTOM_FIELD_VALUE_ID bigint not null auto_increment, CUSTOM_FIELD_ID bigint, MATERIAL_ID bigint, ORDINAL_VALUE integer, value varchar(255), primary key (CUSTOM_FIELD_VALUE_ID)) type=InnoDB;
create table MATERIALS (MATERIAL_ID bigint not null auto_increment, WORKSITE_ID bigint, ACCESS_LEVEL integer, DATE_MODIFIED datetime, text text, THUMB_URL varchar(255), title varchar(255), type varchar(255), url varchar(255), primary key (MATERIAL_ID)) type=InnoDB;
create table PARTICIPANTS (PARTICIPANT_ID bigint not null auto_increment, PARTICIPANT_ID_STRING varchar(255), ACCESS_LEVEL integer, primary key (PARTICIPANT_ID)) type=InnoDB;
create table QUESTIONS (QUESTION_ID bigint not null auto_increment, ASSIGNMENT_ID bigint, ORDINAL_VALUE integer, text text, primary key (QUESTION_ID)) type=InnoDB;
create table QUESTION_MATERIAL_ASSOCS (QUESTION_MATERIAL_ASSOC_ID bigint not null auto_increment, QUESTION_ID bigint, MATERIAL_ID bigint, primary key (QUESTION_MATERIAL_ASSOC_ID)) type=InnoDB;
create table TASTY_ITEMS (ITEM_ID bigint not null auto_increment, name varchar(255), SERVICE_ID bigint, primary key (ITEM_ID)) type=InnoDB;
create table TASTY_ITEM_TAGS (ITEM_TAG_ID bigint not null auto_increment, ITEM_ID bigint, TAG_ID bigint, primary key (ITEM_TAG_ID), unique (ITEM_ID, TAG_ID)) type=InnoDB;
create table TASTY_SERVICES (SERVICE_ID bigint not null auto_increment, name varchar(255), primary key (SERVICE_ID)) type=InnoDB;
create table TASTY_TAGS (TAG_ID bigint not null auto_increment, name varchar(255), SERVICE_ID bigint, primary key (TAG_ID)) type=InnoDB;
create table TASTY_USERS (USER_ID bigint not null auto_increment, name varchar(255), SERVICE_ID bigint, primary key (USER_ID)) type=InnoDB;
create table TASTY_USER_ITEMS (USER_ITEM_ID bigint not null auto_increment, USER_ID bigint, ITEM_ID bigint, primary key (USER_ITEM_ID), unique (USER_ID, ITEM_ID)) type=InnoDB;
create table TASTY_USER_ITEM_TAGS (USER_ITEM_TAG_ID bigint not null auto_increment, USER_ID bigint, ITEM_ID bigint, TAG_ID bigint, primary key (USER_ITEM_TAG_ID), unique (USER_ID, ITEM_ID, TAG_ID)) type=InnoDB;
create table TASTY_USER_TAGS (USER_TAG_ID bigint not null auto_increment, USER_ID bigint, TAG_ID bigint, primary key (USER_TAG_ID), unique (USER_ID, TAG_ID)) type=InnoDB;
create table UCM_COURSES (UCM_COURSE_ID bigint not null auto_increment, COURSE_ID_STRING varchar(255), primary key (UCM_COURSE_ID)) type=InnoDB;
create table UCM_COURSE_WORKSITE_AFFILS (UCM_COURSE_WORKSITE_AFFIL_ID bigint not null auto_increment, UCM_COURSE_ID bigint, UCM_WORKSITE_ID bigint, primary key (UCM_COURSE_WORKSITE_AFFIL_ID)) type=InnoDB;
create table UCM_PARTICIPANTS (UCM_PARTICIPANT_ID bigint not null auto_increment, UCM_USER_ID bigint, UCM_WORKSITE_ID bigint, PARTICIPANT_ID_STRING varchar(255), primary key (UCM_PARTICIPANT_ID)) type=InnoDB;
create table UCM_TERMS (UCM_TERM_ID bigint not null auto_increment, END_DATE datetime, name varchar(255), START_DATE datetime, primary key (UCM_TERM_ID)) type=InnoDB;
create table UCM_USERS (UCM_USER_ID bigint not null auto_increment, USER_ID_STRING varchar(255), email varchar(255), FIRST_NAME varchar(255), LAST_NAME varchar(255), primary key (UCM_USER_ID)) type=InnoDB;
create table UCM_WORKSITES (UCM_WORKSITE_ID bigint not null auto_increment, UCM_TERM_ID bigint, WORKSITE_ID_STRING varchar(255), title varchar(255), primary key (UCM_WORKSITE_ID)) type=InnoDB;
create table UNITS (UNIT_ID bigint not null auto_increment, WORKSITE_ID bigint, title varchar(255), description text, START_DATE datetime, END_DATE datetime, VISIBILITY integer, primary key (UNIT_ID)) type=InnoDB;
create table UNIT_MATERIAL_ASSOCS (UNIT_MATERIAL_ASSOC_ID bigint not null auto_increment, MATERIAL_ID bigint, UNIT_ID bigint, primary key (UNIT_MATERIAL_ASSOC_ID)) type=InnoDB;
create table USERS (USER_ID bigint not null auto_increment, USER_ID_STRING varchar(255), AUTH_METHOD varchar(255), ACCESS_LEVEL integer, password varchar(255), primary key (USER_ID)) type=InnoDB;
create table WORKSITES (WORKSITE_ID bigint not null auto_increment, WORKSITE_ID_STRING varchar(255), announcement text, primary key (WORKSITE_ID)) type=InnoDB;
alter table ANNOTATIONS add index FK47010F047A0F4E9E (PARTICIPANT_ID), add constraint FK47010F047A0F4E9E foreign key (PARTICIPANT_ID) references PARTICIPANTS (PARTICIPANT_ID);
alter table ANNOTATIONS add index FK47010F04491771CA (MATERIAL_ID), add constraint FK47010F04491771CA foreign key (MATERIAL_ID) references MATERIALS (MATERIAL_ID);
alter table ANSWERS add index FKF8494455EBCBF05 (ASSIGNMENT_RESPONSE_ID), add constraint FKF8494455EBCBF05 foreign key (ASSIGNMENT_RESPONSE_ID) references ASSIGNMENT_RESPONSES (ASSIGNMENT_RESPONSE_ID);
alter table ANSWERS add index FKF8494455C3F6856A (QUESTION_ID), add constraint FKF8494455C3F6856A foreign key (QUESTION_ID) references QUESTIONS (QUESTION_ID);
alter table ASSIGNMENTS add index FKE898E726B78970AA (UNIT_ID), add constraint FKE898E726B78970AA foreign key (UNIT_ID) references UNITS (UNIT_ID);
alter table ASSIGNMENT_MATERIAL_ASSOCS add index FK23C7F7A4645FAC0A (ASSIGNMENT_ID), add constraint FK23C7F7A4645FAC0A foreign key (ASSIGNMENT_ID) references ASSIGNMENTS (ASSIGNMENT_ID);
alter table ASSIGNMENT_MATERIAL_ASSOCS add index FK23C7F7A4491771CA (MATERIAL_ID), add constraint FK23C7F7A4491771CA foreign key (MATERIAL_ID) references MATERIALS (MATERIAL_ID);
alter table ASSIGNMENT_RESPONSES add index FK6F169540645FAC0A (ASSIGNMENT_ID), add constraint FK6F169540645FAC0A foreign key (ASSIGNMENT_ID) references ASSIGNMENTS (ASSIGNMENT_ID);
alter table ASSIGNMENT_RESPONSES add index FK6F1695407A0F4E9E (PARTICIPANT_ID), add constraint FK6F1695407A0F4E9E foreign key (PARTICIPANT_ID) references PARTICIPANTS (PARTICIPANT_ID);
alter table COMMENTS add index FKABDCDF4EBCBF05 (ASSIGNMENT_RESPONSE_ID), add constraint FKABDCDF4EBCBF05 foreign key (ASSIGNMENT_RESPONSE_ID) references ASSIGNMENT_RESPONSES (ASSIGNMENT_RESPONSE_ID);
alter table COMMENTS add index FKABDCDF459F0726A (ANSWER_ID), add constraint FKABDCDF459F0726A foreign key (ANSWER_ID) references ANSWERS (ANSWER_ID);
alter table COMMENTS add index FKABDCDF47A0F4E9E (PARTICIPANT_ID), add constraint FKABDCDF47A0F4E9E foreign key (PARTICIPANT_ID) references PARTICIPANTS (PARTICIPANT_ID);
alter table CUSTOM_FIELDS add index FK8566DF47F856EB76 (WORKSITE_ID), add constraint FK8566DF47F856EB76 foreign key (WORKSITE_ID) references WORKSITES (WORKSITE_ID);
alter table CUSTOM_FIELD_VALUES add index FKABA1663534907427 (CUSTOM_FIELD_ID), add constraint FKABA1663534907427 foreign key (CUSTOM_FIELD_ID) references CUSTOM_FIELDS (CUSTOM_FIELD_ID);
alter table CUSTOM_FIELD_VALUES add index FKABA16635491771CA (MATERIAL_ID), add constraint FKABA16635491771CA foreign key (MATERIAL_ID) references MATERIALS (MATERIAL_ID);
alter table MATERIALS add index FKCEB1500CF856EB76 (WORKSITE_ID), add constraint FKCEB1500CF856EB76 foreign key (WORKSITE_ID) references WORKSITES (WORKSITE_ID);
alter table QUESTIONS add index FK3BDD512D645FAC0A (ASSIGNMENT_ID), add constraint FK3BDD512D645FAC0A foreign key (ASSIGNMENT_ID) references ASSIGNMENTS (ASSIGNMENT_ID);
alter table QUESTION_MATERIAL_ASSOCS add index FKF0DF5EBD491771CA (MATERIAL_ID), add constraint FKF0DF5EBD491771CA foreign key (MATERIAL_ID) references MATERIALS (MATERIAL_ID);
alter table QUESTION_MATERIAL_ASSOCS add index FKF0DF5EBDC3F6856A (QUESTION_ID), add constraint FKF0DF5EBDC3F6856A foreign key (QUESTION_ID) references QUESTIONS (QUESTION_ID);
alter table TASTY_ITEMS add index FK141602EC8DF4AFE6 (ITEM_ID), add constraint FK141602EC8DF4AFE6 foreign key (ITEM_ID) references TASTY_SERVICES (SERVICE_ID);
alter table TASTY_ITEMS add index FK141602ECA9042904 (SERVICE_ID), add constraint FK141602ECA9042904 foreign key (SERVICE_ID) references TASTY_SERVICES (SERVICE_ID);
alter table TASTY_ITEM_TAGS add index FK4312F31173F1FE90 (ITEM_TAG_ID), add constraint FK4312F31173F1FE90 foreign key (ITEM_TAG_ID) references TASTY_TAGS (TAG_ID);
alter table TASTY_ITEM_TAGS add index FK4312F311A24B5E75 (ITEM_TAG_ID), add constraint FK4312F311A24B5E75 foreign key (ITEM_TAG_ID) references TASTY_ITEMS (ITEM_ID);
alter table TASTY_ITEM_TAGS add index FK4312F31136904DB0 (ITEM_ID), add constraint FK4312F31136904DB0 foreign key (ITEM_ID) references TASTY_ITEMS (ITEM_ID);
alter table TASTY_ITEM_TAGS add index FK4312F311558D87E4 (TAG_ID), add constraint FK4312F311558D87E4 foreign key (TAG_ID) references TASTY_TAGS (TAG_ID);
alter table TASTY_TAGS add index FK74477F4DDB4B49FF (TAG_ID), add constraint FK74477F4DDB4B49FF foreign key (TAG_ID) references TASTY_SERVICES (SERVICE_ID);
alter table TASTY_TAGS add index FK74477F4DA9042904 (SERVICE_ID), add constraint FK74477F4DA9042904 foreign key (SERVICE_ID) references TASTY_SERVICES (SERVICE_ID);
alter table TASTY_USERS add index FK14BEA93470CE42E (USER_ID), add constraint FK14BEA93470CE42E foreign key (USER_ID) references TASTY_SERVICES (SERVICE_ID);
alter table TASTY_USERS add index FK14BEA934A9042904 (SERVICE_ID), add constraint FK14BEA934A9042904 foreign key (SERVICE_ID) references TASTY_SERVICES (SERVICE_ID);
alter table TASTY_USER_ITEMS add index FK6650E60AFADF2B0 (USER_ID), add constraint FK6650E60AFADF2B0 foreign key (USER_ID) references TASTY_USERS (USER_ID);
alter table TASTY_USER_ITEMS add index FK6650E6036904DB0 (ITEM_ID), add constraint FK6650E6036904DB0 foreign key (ITEM_ID) references TASTY_ITEMS (ITEM_ID);
alter table TASTY_USER_ITEMS add index FK6650E60918555F4 (USER_ITEM_ID), add constraint FK6650E60918555F4 foreign key (USER_ITEM_ID) references TASTY_USERS (USER_ID);
alter table TASTY_USER_ITEMS add index FK6650E60917FE53C (USER_ITEM_ID), add constraint FK6650E60917FE53C foreign key (USER_ITEM_ID) references TASTY_ITEMS (ITEM_ID);
alter table TASTY_USER_ITEM_TAGS add index FK17472485AFADF2B0 (USER_ID), add constraint FK17472485AFADF2B0 foreign key (USER_ID) references TASTY_USERS (USER_ID);
alter table TASTY_USER_ITEM_TAGS add index FK1747248536904DB0 (ITEM_ID), add constraint FK1747248536904DB0 foreign key (ITEM_ID) references TASTY_ITEMS (ITEM_ID);
alter table TASTY_USER_ITEM_TAGS add index FK17472485558D87E4 (TAG_ID), add constraint FK17472485558D87E4 foreign key (TAG_ID) references TASTY_TAGS (TAG_ID);
alter table TASTY_USER_TAGS add index FKD6EF3559AFADF2B0 (USER_ID), add constraint FKD6EF3559AFADF2B0 foreign key (USER_ID) references TASTY_USERS (USER_ID);
alter table TASTY_USER_TAGS add index FKD6EF355981C6CED8 (USER_TAG_ID), add constraint FKD6EF355981C6CED8 foreign key (USER_TAG_ID) references TASTY_TAGS (TAG_ID);
alter table TASTY_USER_TAGS add index FKD6EF3559B0259F75 (USER_TAG_ID), add constraint FKD6EF3559B0259F75 foreign key (USER_TAG_ID) references TASTY_USERS (USER_ID);
alter table TASTY_USER_TAGS add index FKD6EF3559558D87E4 (TAG_ID), add constraint FKD6EF3559558D87E4 foreign key (TAG_ID) references TASTY_TAGS (TAG_ID);
alter table UCM_COURSE_WORKSITE_AFFILS add index FK27FF1C12F6DA3530 (UCM_WORKSITE_ID), add constraint FK27FF1C12F6DA3530 foreign key (UCM_WORKSITE_ID) references UCM_WORKSITES (UCM_WORKSITE_ID);
alter table UCM_COURSE_WORKSITE_AFFILS add index FK27FF1C12C0468FD0 (UCM_COURSE_ID), add constraint FK27FF1C12C0468FD0 foreign key (UCM_COURSE_ID) references UCM_COURSES (UCM_COURSE_ID);
alter table UCM_PARTICIPANTS add index FKF04F6860F6DA3530 (UCM_WORKSITE_ID), add constraint FKF04F6860F6DA3530 foreign key (UCM_WORKSITE_ID) references UCM_WORKSITES (UCM_WORKSITE_ID);
alter table UCM_PARTICIPANTS add index FKF04F68609383750 (UCM_USER_ID), add constraint FKF04F68609383750 foreign key (UCM_USER_ID) references UCM_USERS (UCM_USER_ID);
alter table UCM_WORKSITES add index FK8D3744BBBD2267B0 (UCM_TERM_ID), add constraint FK8D3744BBBD2267B0 foreign key (UCM_TERM_ID) references UCM_TERMS (UCM_TERM_ID);
alter table UNITS add index FK4D25F4FF856EB76 (WORKSITE_ID), add constraint FK4D25F4FF856EB76 foreign key (WORKSITE_ID) references WORKSITES (WORKSITE_ID);
alter table UNIT_MATERIAL_ASSOCS add index FK6ECC085BB78970AA (UNIT_ID), add constraint FK6ECC085BB78970AA foreign key (UNIT_ID) references UNITS (UNIT_ID);
alter table UNIT_MATERIAL_ASSOCS add index FK6ECC085B491771CA (MATERIAL_ID), add constraint FK6ECC085B491771CA foreign key (MATERIAL_ID) references MATERIALS (MATERIAL_ID);
