drop table ANNOTATIONS cascade constraints;
drop table ANSWERS cascade constraints;
drop table ASSIGNMENTS cascade constraints;
drop table ASSIGNMENT_MATERIAL_ASSOCS cascade constraints;
drop table ASSIGNMENT_RESPONSES cascade constraints;
drop table COMMENTS cascade constraints;
drop table CUSTOM_FIELDS cascade constraints;
drop table CUSTOM_FIELD_VALUES cascade constraints;
drop table MATERIALS cascade constraints;
drop table PARTICIPANTS cascade constraints;
drop table QUESTIONS cascade constraints;
drop table QUESTION_MATERIAL_ASSOCS cascade constraints;
drop table TASTY_ITEMS cascade constraints;
drop table TASTY_ITEM_TAGS cascade constraints;
drop table TASTY_SERVICES cascade constraints;
drop table TASTY_TAGS cascade constraints;
drop table TASTY_USERS cascade constraints;
drop table TASTY_USER_ITEMS cascade constraints;
drop table TASTY_USER_ITEM_TAGS cascade constraints;
drop table TASTY_USER_TAGS cascade constraints;
drop table UCM_COURSES cascade constraints;
drop table UCM_COURSE_WORKSITE_AFFILS cascade constraints;
drop table UCM_PARTICIPANTS cascade constraints;
drop table UCM_TERMS cascade constraints;
drop table UCM_USERS cascade constraints;
drop table UCM_WORKSITES cascade constraints;
drop table UNITS cascade constraints;
drop table UNIT_MATERIAL_ASSOCS cascade constraints;
drop table USERS cascade constraints;
drop table WORKSITES cascade constraints;
drop sequence hibernate_sequence;
create table ANNOTATIONS (ANNOTATION_ID number(19,0) not null, MATERIAL_ID number(19,0), PARTICIPANT_ID number(19,0), CLIP_BEGIN varchar2(255 char), CLIP_END varchar2(255 char), DATE_MODIFIED timestamp, text clob, title varchar2(255 char), type varchar2(255 char), primary key (ANNOTATION_ID));
create table ANSWERS (ANSWER_ID number(19,0) not null, ASSIGNMENT_RESPONSE_ID number(19,0), QUESTION_ID number(19,0), STATUS number(10,0), text0 clob, text1 clob, text2 clob, text3 clob, text4 clob, text5 clob, text6 clob, text7 clob, text8 clob, text9 clob, text10 clob, text11 clob, text12 clob, text13 clob, text14 clob, text15 clob, primary key (ANSWER_ID), unique (ASSIGNMENT_RESPONSE_ID, QUESTION_ID));
create table ASSIGNMENTS (ASSIGNMENT_ID number(19,0) not null, UNIT_ID number(19,0), CUSTOM_TYPE varchar2(255 char), DATE_DUE timestamp, instructions clob, ORDINAL_VALUE number(10,0), title varchar2(255 char), type varchar2(255 char), primary key (ASSIGNMENT_ID));
create table ASSIGNMENT_MATERIAL_ASSOCS (ASSIGNMENT_MATERIAL_ASSOC_ID number(19,0) not null, MATERIAL_ID number(19,0), ASSIGNMENT_ID number(19,0), primary key (ASSIGNMENT_MATERIAL_ASSOC_ID));
create table ASSIGNMENT_RESPONSES (ASSIGNMENT_RESPONSE_ID number(19,0) not null, ASSIGNMENT_ID number(19,0), PARTICIPANT_ID number(19,0), DATE_SUBMITTED timestamp, STATUS number(10,0), text0 clob, text1 clob, text2 clob, text3 clob, text4 clob, text5 clob, text6 clob, text7 clob, text8 clob, text9 clob, text10 clob, text11 clob, text12 clob, text13 clob, text14 clob, text15 clob, primary key (ASSIGNMENT_RESPONSE_ID), unique (ASSIGNMENT_ID, PARTICIPANT_ID));
create table COMMENTS (COMMENT_ID number(19,0) not null, ANSWER_ID number(19,0), ASSIGNMENT_RESPONSE_ID number(19,0), PARTICIPANT_ID number(19,0), DATE_MODIFIED timestamp, STATUS number(10,0), text clob, type varchar2(255 char), primary key (COMMENT_ID));
create table CUSTOM_FIELDS (CUSTOM_FIELD_ID number(19,0) not null, WORKSITE_ID number(19,0), name varchar2(255 char), ORDINAL_VALUE number(10,0), visibility number(10,0), primary key (CUSTOM_FIELD_ID));
create table CUSTOM_FIELD_VALUES (CUSTOM_FIELD_VALUE_ID number(19,0) not null, CUSTOM_FIELD_ID number(19,0), MATERIAL_ID number(19,0), ORDINAL_VALUE number(10,0), value varchar2(255 char), primary key (CUSTOM_FIELD_VALUE_ID));
create table MATERIALS (MATERIAL_ID number(19,0) not null, WORKSITE_ID number(19,0), ACCESS_LEVEL number(10,0), DATE_MODIFIED timestamp, text clob, THUMB_URL varchar2(255 char), title varchar2(255 char), type varchar2(255 char), url varchar2(255 char), primary key (MATERIAL_ID));
create table PARTICIPANTS (PARTICIPANT_ID number(19,0) not null, PARTICIPANT_ID_STRING varchar2(255 char), ACCESS_LEVEL number(10,0), primary key (PARTICIPANT_ID));
create table QUESTIONS (QUESTION_ID number(19,0) not null, ASSIGNMENT_ID number(19,0), ORDINAL_VALUE number(10,0), text clob, primary key (QUESTION_ID));
create table QUESTION_MATERIAL_ASSOCS (QUESTION_MATERIAL_ASSOC_ID number(19,0) not null, QUESTION_ID number(19,0), MATERIAL_ID number(19,0), primary key (QUESTION_MATERIAL_ASSOC_ID));
create table TASTY_ITEMS (ITEM_ID number(19,0) not null, name varchar2(255 char), SERVICE_ID number(19,0), primary key (ITEM_ID));
create table TASTY_ITEM_TAGS (ITEM_TAG_ID number(19,0) not null, ITEM_ID number(19,0), TAG_ID number(19,0), primary key (ITEM_TAG_ID), unique (ITEM_ID, TAG_ID));
create table TASTY_SERVICES (SERVICE_ID number(19,0) not null, name varchar2(255 char), primary key (SERVICE_ID));
create table TASTY_TAGS (TAG_ID number(19,0) not null, name varchar2(255 char), SERVICE_ID number(19,0), primary key (TAG_ID));
create table TASTY_USERS (USER_ID number(19,0) not null, name varchar2(255 char), SERVICE_ID number(19,0), primary key (USER_ID));
create table TASTY_USER_ITEMS (USER_ITEM_ID number(19,0) not null, USER_ID number(19,0), ITEM_ID number(19,0), primary key (USER_ITEM_ID), unique (USER_ID, ITEM_ID));
create table TASTY_USER_ITEM_TAGS (USER_ITEM_TAG_ID number(19,0) not null, USER_ID number(19,0), ITEM_ID number(19,0), TAG_ID number(19,0), primary key (USER_ITEM_TAG_ID), unique (USER_ID, ITEM_ID, TAG_ID));
create table TASTY_USER_TAGS (USER_TAG_ID number(19,0) not null, USER_ID number(19,0), TAG_ID number(19,0), primary key (USER_TAG_ID), unique (USER_ID, TAG_ID));
create table UCM_COURSES (UCM_COURSE_ID number(19,0) not null, COURSE_ID_STRING varchar2(255 char), primary key (UCM_COURSE_ID));
create table UCM_COURSE_WORKSITE_AFFILS (UCM_COURSE_WORKSITE_AFFIL_ID number(19,0) not null, UCM_COURSE_ID number(19,0), UCM_WORKSITE_ID number(19,0), primary key (UCM_COURSE_WORKSITE_AFFIL_ID));
create table UCM_PARTICIPANTS (UCM_PARTICIPANT_ID number(19,0) not null, UCM_USER_ID number(19,0), UCM_WORKSITE_ID number(19,0), PARTICIPANT_ID_STRING varchar2(255 char), primary key (UCM_PARTICIPANT_ID));
create table UCM_TERMS (UCM_TERM_ID number(19,0) not null, END_DATE timestamp, name varchar2(255 char), START_DATE timestamp, primary key (UCM_TERM_ID));
create table UCM_USERS (UCM_USER_ID number(19,0) not null, USER_ID_STRING varchar2(255 char), email varchar2(255 char), FIRST_NAME varchar2(255 char), LAST_NAME varchar2(255 char), primary key (UCM_USER_ID));
create table UCM_WORKSITES (UCM_WORKSITE_ID number(19,0) not null, UCM_TERM_ID number(19,0), WORKSITE_ID_STRING varchar2(255 char), title varchar2(255 char), primary key (UCM_WORKSITE_ID));
create table UNITS (UNIT_ID number(19,0) not null, WORKSITE_ID number(19,0), title varchar2(255 char), description clob, START_DATE timestamp, END_DATE timestamp, VISIBILITY number(10,0), primary key (UNIT_ID));
create table UNIT_MATERIAL_ASSOCS (UNIT_MATERIAL_ASSOC_ID number(19,0) not null, MATERIAL_ID number(19,0), UNIT_ID number(19,0), primary key (UNIT_MATERIAL_ASSOC_ID));
create table USERS (USER_ID number(19,0) not null, USER_ID_STRING varchar2(255 char), AUTH_METHOD varchar2(255 char), ACCESS_LEVEL number(10,0), password varchar2(255 char), primary key (USER_ID));
create table WORKSITES (WORKSITE_ID number(19,0) not null, WORKSITE_ID_STRING varchar2(255 char), announcement clob, primary key (WORKSITE_ID));
alter table ANNOTATIONS add constraint FK47010F047A0F4E9E foreign key (PARTICIPANT_ID) references PARTICIPANTS;
alter table ANNOTATIONS add constraint FK47010F04491771CA foreign key (MATERIAL_ID) references MATERIALS;
alter table ANSWERS add constraint FKF8494455EBCBF05 foreign key (ASSIGNMENT_RESPONSE_ID) references ASSIGNMENT_RESPONSES;
alter table ANSWERS add constraint FKF8494455C3F6856A foreign key (QUESTION_ID) references QUESTIONS;
alter table ASSIGNMENTS add constraint FKE898E726B78970AA foreign key (UNIT_ID) references UNITS;
alter table ASSIGNMENT_MATERIAL_ASSOCS add constraint FK23C7F7A4645FAC0A foreign key (ASSIGNMENT_ID) references ASSIGNMENTS;
alter table ASSIGNMENT_MATERIAL_ASSOCS add constraint FK23C7F7A4491771CA foreign key (MATERIAL_ID) references MATERIALS;
alter table ASSIGNMENT_RESPONSES add constraint FK6F169540645FAC0A foreign key (ASSIGNMENT_ID) references ASSIGNMENTS;
alter table ASSIGNMENT_RESPONSES add constraint FK6F1695407A0F4E9E foreign key (PARTICIPANT_ID) references PARTICIPANTS;
alter table COMMENTS add constraint FKABDCDF4EBCBF05 foreign key (ASSIGNMENT_RESPONSE_ID) references ASSIGNMENT_RESPONSES;
alter table COMMENTS add constraint FKABDCDF459F0726A foreign key (ANSWER_ID) references ANSWERS;
alter table COMMENTS add constraint FKABDCDF47A0F4E9E foreign key (PARTICIPANT_ID) references PARTICIPANTS;
alter table CUSTOM_FIELDS add constraint FK8566DF47F856EB76 foreign key (WORKSITE_ID) references WORKSITES;
alter table CUSTOM_FIELD_VALUES add constraint FKABA1663534907427 foreign key (CUSTOM_FIELD_ID) references CUSTOM_FIELDS;
alter table CUSTOM_FIELD_VALUES add constraint FKABA16635491771CA foreign key (MATERIAL_ID) references MATERIALS;
alter table MATERIALS add constraint FKCEB1500CF856EB76 foreign key (WORKSITE_ID) references WORKSITES;
alter table QUESTIONS add constraint FK3BDD512D645FAC0A foreign key (ASSIGNMENT_ID) references ASSIGNMENTS;
alter table QUESTION_MATERIAL_ASSOCS add constraint FKF0DF5EBD491771CA foreign key (MATERIAL_ID) references MATERIALS;
alter table QUESTION_MATERIAL_ASSOCS add constraint FKF0DF5EBDC3F6856A foreign key (QUESTION_ID) references QUESTIONS;
alter table TASTY_ITEMS add constraint FK141602EC8DF4AFE6 foreign key (ITEM_ID) references TASTY_SERVICES;
alter table TASTY_ITEMS add constraint FK141602ECA9042904 foreign key (SERVICE_ID) references TASTY_SERVICES;
alter table TASTY_ITEM_TAGS add constraint FK4312F31173F1FE90 foreign key (ITEM_TAG_ID) references TASTY_TAGS;
alter table TASTY_ITEM_TAGS add constraint FK4312F311A24B5E75 foreign key (ITEM_TAG_ID) references TASTY_ITEMS;
alter table TASTY_ITEM_TAGS add constraint FK4312F31136904DB0 foreign key (ITEM_ID) references TASTY_ITEMS;
alter table TASTY_ITEM_TAGS add constraint FK4312F311558D87E4 foreign key (TAG_ID) references TASTY_TAGS;
alter table TASTY_TAGS add constraint FK74477F4DDB4B49FF foreign key (TAG_ID) references TASTY_SERVICES;
alter table TASTY_TAGS add constraint FK74477F4DA9042904 foreign key (SERVICE_ID) references TASTY_SERVICES;
alter table TASTY_USERS add constraint FK14BEA93470CE42E foreign key (USER_ID) references TASTY_SERVICES;
alter table TASTY_USERS add constraint FK14BEA934A9042904 foreign key (SERVICE_ID) references TASTY_SERVICES;
alter table TASTY_USER_ITEMS add constraint FK6650E60AFADF2B0 foreign key (USER_ID) references TASTY_USERS;
alter table TASTY_USER_ITEMS add constraint FK6650E6036904DB0 foreign key (ITEM_ID) references TASTY_ITEMS;
alter table TASTY_USER_ITEMS add constraint FK6650E60918555F4 foreign key (USER_ITEM_ID) references TASTY_USERS;
alter table TASTY_USER_ITEMS add constraint FK6650E60917FE53C foreign key (USER_ITEM_ID) references TASTY_ITEMS;
alter table TASTY_USER_ITEM_TAGS add constraint FK17472485AFADF2B0 foreign key (USER_ID) references TASTY_USERS;
alter table TASTY_USER_ITEM_TAGS add constraint FK1747248536904DB0 foreign key (ITEM_ID) references TASTY_ITEMS;
alter table TASTY_USER_ITEM_TAGS add constraint FK17472485558D87E4 foreign key (TAG_ID) references TASTY_TAGS;
alter table TASTY_USER_TAGS add constraint FKD6EF3559AFADF2B0 foreign key (USER_ID) references TASTY_USERS;
alter table TASTY_USER_TAGS add constraint FKD6EF355981C6CED8 foreign key (USER_TAG_ID) references TASTY_TAGS;
alter table TASTY_USER_TAGS add constraint FKD6EF3559B0259F75 foreign key (USER_TAG_ID) references TASTY_USERS;
alter table TASTY_USER_TAGS add constraint FKD6EF3559558D87E4 foreign key (TAG_ID) references TASTY_TAGS;
alter table UCM_COURSE_WORKSITE_AFFILS add constraint FK27FF1C12F6DA3530 foreign key (UCM_WORKSITE_ID) references UCM_WORKSITES;
alter table UCM_COURSE_WORKSITE_AFFILS add constraint FK27FF1C12C0468FD0 foreign key (UCM_COURSE_ID) references UCM_COURSES;
alter table UCM_PARTICIPANTS add constraint FKF04F6860F6DA3530 foreign key (UCM_WORKSITE_ID) references UCM_WORKSITES;
alter table UCM_PARTICIPANTS add constraint FKF04F68609383750 foreign key (UCM_USER_ID) references UCM_USERS;
alter table UCM_WORKSITES add constraint FK8D3744BBBD2267B0 foreign key (UCM_TERM_ID) references UCM_TERMS;
alter table UNITS add constraint FK4D25F4FF856EB76 foreign key (WORKSITE_ID) references WORKSITES;
alter table UNIT_MATERIAL_ASSOCS add constraint FK6ECC085BB78970AA foreign key (UNIT_ID) references UNITS;
alter table UNIT_MATERIAL_ASSOCS add constraint FK6ECC085B491771CA foreign key (MATERIAL_ID) references MATERIALS;
create sequence hibernate_sequence;
